baseURL = "https://shohi.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Shohi Wang"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "even"
enableGitInfo = true # use git commit log to generate lastmod record

# Syntax highlighting by Chroma.
# NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = true     # has chinese/japanese/korean?
paginate = 10
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name

[author]                  # essential
  name = "Shohi Wang"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu
  name = "Latest"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tag"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Catogery"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Link"
  weight = 50
  identifier = "link"
  url = "/link/"
[[menu.main]]
  name = "About"
  weight = 60
  identifier = "about"
  url = "/about/"

[params]
  # Used to give a friendly message when you have an incompatible update
  version = "4.x"

  # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  debug = false

  # Site creation time
  since = "2020"

  # use public git repo url to link lastmod git commit
  # enableGitInfo should be true.
  gitRepo = "https://github.com/shohi/shohi.github.io"

  # site info (optional)
  logoTitle = "Imagine & Possibility"        # default: the title value
  # logoTitle = "Mindful"
  keywords = ["Hugo", "theme","even"]
  description = "Shohi Wang's personal blog site."

  # paginate of archives, tags and categories
  archivePaginate = 50

  # show 'xx Posts In Total' in archive page?
  showArchiveCount = true

  # The date format to use; for a list of valid formats
  # see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time?
  moreMeta = true

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # Some global options, you can also close or open something in front
  # matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  autoCollapseToc = false

  # see https://github.com/fancyapps/fancybox (e.g. image is clickable)
  fancybox = true

  # see https://www.mathjax.org/
  mathjax = true
  # inline $...$ latex rendering
  mathjaxEnableSingleDollar = true
  mathjaxEnableAutoNumber = false
  # You should install mathjax in `your-site/static/lib/mathjax`
  mathjaxUseLocalFiles = false

  # contain author, lastMod, markdown link, license
  postMetaInFooter = true

  # Only effective when hugo will output .md files.
  linkToMarkDown = false
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Changyan app id/key
  changyanAppid = ""
  changyanAppkey = ""

  # liver uid/key
  livereUID = ""

  # Baidu push and analytics
  baiduPush = false
  baiduAnalytics = ""

  # Verification
  baiduVerification = ""
  googleVerification = ""

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  # please keep same with uglyurls setting
  uglyURLs = false

  # Show language selector for multilingual site.
  showLanguageSelector = false

  # load these files from public cdn
  [params.publicCDN]
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJS = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
    timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
    timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
    flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
    sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
    sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

  # Display a message at the beginning of an article to warn the readers
  # that it's content may be outdated.
  [params.outdatedInfoWarning]
    enable = false

    # Display hint if the last modified time is more than these days ago
    hint = 30

    # # Display warning if the last modified time is more than these days ago
    warn = 180

  # Gitment is a comment system based on GitHub issues.
  # see https://github.com/imsun/gitment
  [params.gitment]
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.utterances]       # https://utteranc.es/
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments

  [params.gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = false
    appId = ''
    appKey = ''
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'mm'
    placeholder = ''
    visitor = false

  # see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
  [params.flowchartDiagrams]
    enable = false
    options = ""

  # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
  [params.sequenceDiagrams]
    enable = false
    options = ""            # default: "{theme: 'simple'}"

  [params.busuanzi]         # count web traffic by busuanzi
    enable = false
    siteUV = true
    sitePV = true
    pagePV = true

  [params.reward]                                         # 文章打赏
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
    alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

  [params.social]                                         # 社交链接
    # a-email = "mailto:user@example.com"
    # b-stack-overflow = "http://localhost:1313"
    # d-facebook = "http://localhost:1313"
    # f-google = "http://localhost:1313"
    g-github = "http://github.com/shohi"
    # h-weibo = "http://localhost:1313"
    # i-zhihu = "http://localhost:1313"
    # j-douban = "http://localhost:1313"
    # k-pocket = "http://localhost:1313"
    # l-tumblr = "http://localhost:1313"
    # m-instagram = "http://localhost:1313"
    # n-gitlab = "http://localhost:1313"
    # o-bilibili = "http://localhost:1313"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# see https://gohugo.io/getting-started/configuration-markup
[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
